#!/usr/bin/env bash

set -e

cli_apps=(
  "bat;bat"
  "broot;broot"
  "delta;git-delta"
  "rg;ripgrep"
  "fd;fd-find"
  "as-tree;-f --git https://github.com/jez/as-tree"
  "btm;bottom"
  "exa;exa"
)

for ((i = 0; i < ${#cli_apps[@]}; i++)); do
  IFS=';' read -r cli_app exec_install <<<"${cli_apps[i]}"
  if ! [ -x "$(command -v "${cli_app}")" ]; then
    echo-run cargo install --locked "${exec_install}"
  else
    echo-info "cli app: ${cli_app} is already installed"
  fi
  unset IFS
done
