#!/bin/sh

set -e

cli_apps="
bat;bat
broot;broot
btm;bottom
delta;git-delta
difft;difftastic
dust;du-dust
eza;eza
fd;fd-find
just;just
lsd;lsd
macchina;macchina
monolith;monolith
navi;navi
ouch;ouch
procs;procs
rg;ripgrep
sd;sd
selene;selene
stylua;stylua
taplo;taplo-cli
tldr;tealdeer
tokei;tokei
xplr;xplr
zoxide;zoxide
"

for cli_app in $cli_apps; do
	cli_app_name=$(echo "$cli_app" | cut -d ';' -f 1)
	cargo_package=$(echo "$cli_app" | cut -d ';' -f 2-)
	echo-info "cli app: installing $cli_app_name"
	echo-run cargo install --locked --force "$cargo_package" || true
done
