#!/usr/bin/env bash

set -e

cli_apps=(
  "dyff;github.com/homeport/dyff/cmd/dyff@latest"
  "gmailctl;github.com/mbrt/gmailctl/cmd/gmailctl@latest"
  "gopls;golang.org/x/tools/gopls@latest"
  "jsonnet-deps;github.com/google/go-jsonnet/cmd/jsonnet-deps@latest"
  "jsonnet-lint;github.com/google/go-jsonnet/cmd/jsonnet-lint@latest"
  "jsonnet;github.com/google/go-jsonnet/cmd/jsonnet@latest"
  "jsonnetfmt;github.com/google/go-jsonnet/cmd/jsonnetfmt@latest"
  "k9s;github.com/derailed/k9s@latest"
  "kubectx;github.com/ahmetb/kubectx/cmd/kubectx@latest"
  "kubens;github.com/ahmetb/kubectx/cmd/kubens@latest"
  "pistol;github.com/doronbehar/pistol/cmd/pistol@latest"
  "yq;github.com/mikefarah/yq/v4@latest"
)

for ((i = 0; i < ${#cli_apps[@]}; i++)); do
  IFS=';' read -r cli_app go_pkg <<<"${cli_apps[i]}"
  if ! [ -x "$(command -v "${cli_app}")" ]; then
    echo-run go install "${go_pkg}"
  else
    echo-info "cli app: ${cli_app} is already installed"
  fi
  unset IFS
done
