#!/usr/bin/env bash

set -e

cli_apps=(
	"as-tree;--git https://github.com/jez/as-tree"
	"bat;bat"
	"broot;broot"
	"btm;bottom"
	"delta;git-delta"
	"difft;difftastic"
	"dust;du-dust"
	"exa;exa"
	"fd;fd-find"
	"gitui;gitui"
	"just;just"
	"macchina;macchina"
	"monolith;monolith"
	"ouch;ouch"
	"procs;procs"
	"rg;ripgrep"
	"sd;sd"
	"tokei;tokei"
	"zoxide;zoxide"
)

for ((i = 0; i < ${#cli_apps[@]}; i++)); do
	IFS=';' read -r cli_app cargo_package <<<"${cli_apps[i]}"
	echo-info "cli app: installing ${cli_app}"
	echo-run cargo install -f ${cargo_package}
	unset IFS
done
