# cargo: — Rust crates installed from crates.io.
[tools]
"cargo:broot"        = "latest"
"cargo:zsh-patina"   = "latest"
"cargo:codebook-lsp" = "latest"
"cargo:eza"          = "latest"
"cargo:ghgrab"       = "latest"
"cargo:harper-ls"    = "latest"
"cargo:hurl"         = "latest"
"cargo:jiq"          = "latest"
"cargo:monolith"     = "latest"
"cargo:navi"         = "latest"
"cargo:ouch"         = "latest"
"cargo:procs"        = "latest"
"cargo:rip-cli"      = "latest"
"cargo:scooter"      = "latest"
"cargo:sd"           = "latest"
"cargo:selene"       = "latest"
"cargo:sqruff"       = "latest"
"cargo:tealdeer"     = "latest"
"cargo:treemd"       = "latest"
"cargo:vivid"        = "latest"
