require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "arduino",
    "bash",
    "c",
    "clojure",
    "cmake",
    "comment",
    "commonlisp",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "elixir",
    "erlang",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "git_config",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "gowork",
    "graphql",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "jsonnet",
    "kotlin",
    "latex",
    "lua",
    "luap",
    "make",
    "markdown",
    "proto",
    "python",
    "ron",
    "rst",
    "ruby",
    "rust",
    "scss",
    "terraform",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
  ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { 'help' }, -- list of language that will be disabled
  },
  rainbow = {
    enable = true,
    extended_mode = true,
    max_file_lines = nil,
  },
}
