return {
  'windwp/nvim-ts-autotag',
  ft = {
    'astro',
    'glimmer',
    'handlebars',
    'html',
    'javascript',
    'javascriptreact',
    'jsx',
    'liquid',
    'markdown',
    'php',
    'rescript',
    'svelte',
    'tsx',
    'twig',
    'typescript',
    'typescriptreact',
    'vue',
    'xml',
  },
  dependencies = { 'nvim-treesitter/nvim-treesitter' },
  config = function() require('nvim-ts-autotag').setup() end,
}
