#!/bin/sh

die() {
	echo-err "$1" >&2
	exit 1
}

__new_session() {
	[ "$#" -eq 0 ] && die "You need to pass in a session name"
	tmux new-session -s "$1"
}

__kill_server() {
	tmux kill-server
}

__kill_session() {
	[ "$#" -eq 0 ] && die "You need to pass in a tmux session"
	tmux kill-session -t "$1"
}

__list_sessions() {
	tmux ls
}

__attach() {
	[ "$#" -eq 0 ] && die "You need to pass in a tmux session"
	tmux attach -d -t "$1"
}

tmux_command=""
while [ "$#" -ne 0 ]; do
	case "$1" in
	ns | new-session)
		tmux_command="new-session"
		shift
		;;
	ksv | kill-server)
		tmux_command="kill-server"
		shift
		;;
	ks | kill-session)
		tmux_command="kill-session"
		shift
		;;
	l | list-sessions)
		tmux_command="list-sessions"
		shift
		;;
	a | attach)
		tmux_command="attach"
		shift
		;;
	--*= | -*) # unsupported flags
		die "unsupported flag $1"
		;;
	*) # preserve positional arguments
		break
		;;
	esac
done

case "$tmux_command" in
new-session)
	__new_session "$@"
	;;
kill-server)
	__kill_server
	;;
kill-session)
	__kill_session "$@"
	;;
list-sessions)
	__list_sessions
	;;
attach)
	__attach "$@"
	;;
*)
	die "unsupported command $tmux_command"
	;;
esac
