#!/usr/bin/env bash
# ============================================================================
# entrypoint.sh — Preflight gate for brownie (extended AiderDesk image).
#
# Checks:
#   1. `git` is installed and on PATH
#   2. GIT_USER_NAME and GIT_USER_EMAIL env vars are set
#   3. Generates a minimal git config from those env vars
#   4. If GIT_SIGNING_KEY is set:
#      a. Adds SSH signing block to the generated config
#      b. Verifies SSH_AUTH_SOCK points to a live agent socket
#
# All mounts (project dir, AiderDesk config, SSH agent socket) are the
# caller's responsibility. This entrypoint generates git config and
# validates the environment.
# ============================================================================
set -euo pipefail

GIT_CONFIG_DIR="${XDG_CONFIG_HOME:-/etc/xdg}/git"
GIT_CONFIG_FILE="${GIT_CONFIG_DIR}/config"

errors=0

# ── Check: git binary ──────────────────────────────────────────────────
if ! command -v git &>/dev/null; then
  echo "FATAL: 'git' binary not found on PATH." >&2
  errors=$((errors + 1))
else
  echo "✓ git      $(git --version)"
fi

# ── Check: required identity env vars ─────────────────────────────────
if [ -z "${GIT_USER_NAME:-}" ]; then
  echo "FATAL: GIT_USER_NAME is not set." >&2
  echo "       Pass it via: -e GIT_USER_NAME=\"Your Name\"" >&2
  errors=$((errors + 1))
fi

if [ -z "${GIT_USER_EMAIL:-}" ]; then
  echo "FATAL: GIT_USER_EMAIL is not set." >&2
  echo "       Pass it via: -e GIT_USER_EMAIL=\"you@example.com\"" >&2
  errors=$((errors + 1))
fi

# Abort early if identity is missing — can't generate config without it
if [ "${errors}" -gt 0 ]; then
  echo "" >&2
  echo "Startup aborted — ${errors} preflight check(s) failed." >&2
  exit 1
fi

echo "✓ ident    ${GIT_USER_NAME} <${GIT_USER_EMAIL}>"

# ── Generate minimal git config ──────────────────────────────────────
mkdir -p "${GIT_CONFIG_DIR}"

cat >"${GIT_CONFIG_FILE}" <<EOF
# Generated by brownie entrypoint — do not edit
[user]
  name = ${GIT_USER_NAME}
  email = ${GIT_USER_EMAIL}
EOF

# SSH signing block (only if a signing key is provided)
if [ -n "${GIT_SIGNING_KEY:-}" ]; then
  sign_commits="${GIT_SIGN_COMMITS:-true}"

  cat >>"${GIT_CONFIG_FILE}" <<EOF
  signingkey = ${GIT_SIGNING_KEY}

[gpg]
  format = ssh

[gpg "ssh"]
  program = ssh-keygen

[commit]
  gpgsign = ${sign_commits}

[tag]
  gpgsign = ${sign_commits}
EOF

  echo "✓ sign     format=ssh  gpgsign=${sign_commits}"
  echo "  ↳ key    ${GIT_SIGNING_KEY:0:40}..."
  echo "  ↳ prog   ssh-keygen (via SSH_AUTH_SOCK)"
fi

# Sensible defaults for container use
cat >>"${GIT_CONFIG_FILE}" <<EOF

[push]
  default = current

[pull]
  rebase = true

[init]
  defaultBranch = main
EOF

echo "✓ gitcfg   ${GIT_CONFIG_FILE} (generated)"

# ── Check: SSH agent (if signing is configured) ──────────────────────
if [ -n "${GIT_SIGNING_KEY:-}" ]; then
  if [ -z "${SSH_AUTH_SOCK:-}" ]; then
    echo "FATAL: GIT_SIGNING_KEY is set but SSH_AUTH_SOCK is not." >&2
    echo "       Mount the 1Password agent socket:" >&2
    echo "         -v ~/.1password/agent.sock:/run/1password/agent.sock" >&2
    echo "         -e SSH_AUTH_SOCK=/run/1password/agent.sock" >&2
    errors=$((errors + 1))
  elif [ ! -S "${SSH_AUTH_SOCK}" ]; then
    echo "FATAL: SSH_AUTH_SOCK='${SSH_AUTH_SOCK}' is not a socket." >&2
    echo "       Ensure the 1Password SSH agent socket is mounted." >&2
    errors=$((errors + 1))
  else
    if agent_output=$(ssh-add -l 2>&1); then
      key_count=$(echo "${agent_output}" | wc -l)
      echo "  ↳ agent  ${SSH_AUTH_SOCK} (${key_count} identity/ies)"
    elif echo "${agent_output}" | grep -q "no identities"; then
      echo "  ↳ agent  ${SSH_AUTH_SOCK} (no identities yet — 1Password loads on demand)"
    else
      echo "FATAL: SSH agent at ${SSH_AUTH_SOCK} is not responding." >&2
      echo "       ssh-add -l returned: ${agent_output}" >&2
      errors=$((errors + 1))
    fi
  fi
fi

# ── Abort if anything failed ──────────────────────────────────────────
if [ "${errors}" -gt 0 ]; then
  echo "" >&2
  echo "Startup aborted — ${errors} preflight check(s) failed." >&2
  exit 1
fi

echo ""
echo "Preflight OK — launching: $*"
exec "$@"
