#!/bin/sh

set -o errexit

log_newline='true'
if [ "$1" = "-n" ]; then
  log_newline='false'
  shift
fi

log_level="$1"
log_color=""
shift

if [ "${1:-}" = "-n" ]; then
  log_newline='false'
  shift
fi

case "$log_level" in
DEBUG | TRACE)
  log_level="DEBUG"
  log_color="\033[38;5;39m"
  ;;
OK | SUCCESS)
  log_level="SUCCESS"
  log_color="\033[38;5;76m"
  ;;
WARN)
  log_color="\033[38;5;214m"
  ;;
ERROR | ERR)
  log_level="ERROR"
  log_color="\033[38;5;167m"
  ;;
FATAL)
  log_color="\033[38;5;124m"
  ;;
INFO)
  log_color="\033[38;5;34m"
  ;;
*)
  set -- "$log_level" "$@"
  log_level="INFO"
  log_color="\033[38;5;34m"
  ;;
esac

if [ -n "${LOG_DATE:-}" ]; then
  printf '%s ' "$(echo-date)"
fi

printf "%b[%s] ---\033[0m " "$log_color" "$log_level"

if $log_newline; then
  unset log_color log_level log_newline
  echo "$@"
else
  unset log_color log_level log_newline
  printf "%s" "$@"
fi
